In [ ]:
import pandas as pd
import numpy as np

In [ ]:
mySeries = pd.Series([1,2,3,4], index = ['a','b','c','d'])
mySeries[['a','d']]

a    1
d    4
dtype: int64

In [ ]:
data = pd.Series([1,2,3,4,5])

In [ ]:
print(data)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
my_array = np.array([2,3,4,5,6])
series_dt = pd.Series([my_array])
#series_dt = pd.Series([np.array([2,3,4,5])])
series_dt

0    [2, 3, 4, 5, 6]
dtype: object

In [ ]:
data[2]

3

In [ ]:
data = pd.Series(["Sabtu","siang","6-8-2022"], index=["a","b","c"])
data

a       Sabtu
b       siang
c    6-8-2022
dtype: object

In [ ]:
data["b"]

'siang'

# **Creating Dataframe**

In [ ]:
data = ["sabtu","siang","6-8-2022"]
df_array = np.array([[" ","Waktu"],
                     ["Hari","Sabtu"],
                     ["Tanggal","6-8-2022"]])

In [ ]:
data

['sabtu', 'siang', '6-8-2022']

In [ ]:
df = pd.DataFrame(data=df_array)
df

0         1
0              Waktu
1     Hari     Sabtu
2  Tanggal  6-8-2022

In [ ]:
data = np.array([["", "Kolom1","Kolom2"],
                 ["Baris1",1,2],
                 ["Baris2",3,4]])

In [ ]:
print(pd.DataFrame(data=data[1:,1:],
                   index=data[1:,0:],
                   columns=data[0,1:]))

               Kolom1 Kolom2
(Baris1, 1, 2)      1      2
(Baris2, 3, 4)      3      4


In [ ]:
df = pd.DataFrame(data=df_array[1:,1:],
                  index=df_array[1:,0:],
                  columns=df_array[0,1:])

In [ ]:
df

Waktu
(Hari, Sabtu)           Sabtu
(Tanggal, 6-8-2022)  6-8-2022

# **Membuat Dataframe dari 2D Array**

In [ ]:
my_2darray = np.array([[1,2,3],[4,5,6]])
print(my_2darray)

[[1 2 3]
 [4 5 6]]


In [ ]:
df_array2 = pd.DataFrame(data=my_2darray,
                         index=range(0,2),
                         columns=[1,2,3])
print(df_array2)

   1  2  3
0  1  2  3
1  4  5  6


In [ ]:
second_array = my_2darray[0:2,0:2]
second_array

array([[1, 2],
       [4, 5]])

In [ ]:
#Latihan buat dari my_2darray
df_2darray = pd.DataFrame(data=second_array,
                          index=range(0,2),
                          columns=['A','B'])
df_2darray

A  B
0  1  2
1  4  5

# Series with Dictionary

In [ ]:
my_series = pd.Series({"Jabar":"Bandung","Jateng":"Semarang","Jatim":"Surabaya","Bali":"Denpasar"})
my_series

Jabar      Bandung
Jateng    Semarang
Jatim     Surabaya
Bali      Denpasar
dtype: object

In [ ]:
# Latihan buat series
# Gunakan Item
df_series = pd.DataFrame(data=my_series.items(),
                         index=range(0,4),
                         columns=['Provinsi', 'Ibu Kota'])
df_series

Provinsi  Ibu Kota
0    Jabar   Bandung
1   Jateng  Semarang
2    Jatim  Surabaya
3     Bali  Denpasar

In [ ]:
#isi value per column
df = pd.DataFrame({"A": [1,2,3,4,5],
                   "B": [6,7,8,9,10],
                   "C": [11,12,13,14,15]})
df.head()

A   B   C
0  1   6  11
1  2   7  12
2  3   8  13
3  4   9  14
4  5  10  15

In [ ]:
#
df_series2 = pd.DataFrame({"Provinsi":["Jabar","Jateng","Jatim","Bali"],
                           "Ibu Kota":["Bandung","Semarang","Surabaya","Denpasar"]})
df_series2

Provinsi  Ibu Kota
0    Jabar   Bandung
1   Jateng  Semarang
2    Jatim  Surabaya
3     Bali  Denpasar

# Selecting

In [ ]:
#Menggunakan iloc[] -> pada posisi di indeks, jadi akan mencari nilai DataFrame yang berada pada index x
print(df.iloc[2])

A     3
B     8
C    13
Name: 2, dtype: int64


In [ ]:
#Menggunakan iloc[] -> ambil nilai pada indeks baris ke-o dan indeks kolom ke-0
print(df.iloc[0][0])

1


In [ ]:
#Menggunakan iloc[] -> ambil semua elemen indes 0-1
print(df.iloc[:,0:2])

   A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10


In [ ]:
#Menggunakan at -> ambil index label x dari nama kolom y
print(df.at[2,'A'])

3


In [ ]:
#Menggunakan iat -> ambil index baris x dari nama kolom y
print(df.iat[4,2])

15


In [ ]:
df[['A','C']]

A   C
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15

# Read/Write DF

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df_csv = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Iris.csv')

In [ ]:
df_csv.head

<bound method NDFrame.head of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa

In [ ]:
df_csv

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [ ]:
df_csv.shape

(150, 6)

In [ ]:
#write excel
df_csv.to_excel('/content/drive/MyDrive/Colab Notebooks/Iris.xlsx', sheet_name='dataset',index=False)

In [ ]:
#read excel
df_excel = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Iris.xlsx')
df_excel.head

<bound method NDFrame.head of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa